### ISSUE TITLE
Rename package

### ISSUE THREAD

**Issue by carlobaldassi** [JuliaArchive/Options.jl#4]
In light of the recent auto-require changes, this package should probably be renamed to OptionsMod, so that `using OptionsMod` is sufficient to load it.

Either that, or the module name should be changed to `Options` and the type to something else (`Opts`?).

**Comment by s2maki** [comment]
If this is going to get renamed, I would hope for a better name than OptionsMod or Opts.  Neither of these (nor Options) is particularly descriptive.  I would quote point four from the documentation:

> Err on the side of clarity, even if clarity seems long-winded to you.

**Comment by kmsquire** [comment]
@s2maki, this package was written before keyword arguments existed in Julia, and is still around for compatibility purposes for older packages.  It should be deprecated at some point, and probably won't be renamed.

For newer code (or old code that you want to upgrade), check out http://docs.julialang.org/en/release-0.3/manual/functions/#keyword-arguments.

**Comment by kmsquire** [comment]
(Closing this.  If it's still relevant for some reason, please reopen.)

**Comment by carlobaldassi** [comment]
This package is still used by ArgParse, see https://github.com/carlobaldassi/ArgParse.jl/issues/13.
There's also a new issue with the name because of the recent `require` deprecation. The switch to `import` (see https://github.com/carlobaldassi/ArgParse.jl/pull/14/files) gives a warning because the module name is different from the file name. So now it is not clear how to load this package without getting a warning.

**Comment by kmsquire** [comment]
Thanks for the clarification, @carlobaldassi.

**Comment by StefanKarpinski** [comment]
@carlobaldassi, how much work would it be to make ArgParse not use Options? Or are you keeping it as is for compatibility with 0.2?

**Comment by carlobaldassi** [comment]
Compatibility with 0.2 is not a priority of mine, just a consequence of the fact that I did not have the need to bump the version until now.
Removing the Options dependency from ArgParse is something which I could work on, but I'm not sure when (I don't have much time lately, unfortunately). It would also be breaking, although not dramatically so. Anyway, if the general consensus is to retire Options as a package I could certainly work on that at some point.

**Comment by StefanKarpinski** [comment]
Yes, there's no hurry, but I think that once 0.4 is out, deprecating all use of 0.2 would make sense.

**Comment by carlobaldassi** [comment]
Update: I have now updated ArgParse to avoid the dependency on this package.
The name should still be changed IMO (it still has some nice functionality which is not 100% covered by keyword arguments - and I vote for OptionsMod for simplicity), but at least this is not preventing precompilation of other packages now.

**Comment by StefanKarpinski** [comment]
What functionality does it have that keywords don't? I'd really like to get rid of Options.jl, tbh...

**Comment by tkelman** [comment]
No recent versions of anything still use this. It should probably just be deprecated and moved to JuliaArchive. @carlobaldassi I sent you an invite to that org.

**Comment by tkelman** [comment]
Renaming packages after they've been registered is kind of a pain. I moved this to JuliaArchive and we can think about officially deprecating it in METADATA.
